---
# Telegram API ID and hash from the Telegram dev portal.
# Signup for it here: https://my.telegram.org/auth?to=apps
# You can remove api_id and api_hash here, and instead,
# pass the environment variables API_ID and API_HASH to tg-archive
api_id: "123456"
api_hash: "your_api_hash"

# Telegram channel / group name or your group username or your group id(a negative number) to import. 
# Your user account that was used to creat the API ID should 
# be a member of this group.

group: "your_group_name or your_group_username or your_group_id(a negative number)"

# Avatars and media will be downloaded into media_dir.
download_media: True
download_avatars: True
avatar_size: [64, 64] # Width, Height.
media_dir: "media"

# The list of media/file mime types (in lowercase) to download.
# eg: ["image/gif", "image/jpeg", "image/png", "video/mp4", "application/zip", "application/pdf"]
# If left empty, files of all types are downloaded.
media_mime_types: []

# Takeout mode allows you to fetch messages at a higher rate than the standard mode.
# It is the method used in the desktop client to export data.
# You can use a larger fetch_batch_size. Set this as False to use the standard mode.
use_takeout: False

# Use a proxy to access Telegram
# https://github.com/LonamiWebs/Telethon/blob/master/readthedocs/basic/signing-in.rst#signing-in-behind-a-proxy
proxy:
  enable: False
  protocol: "socks5"
  addr: "127.0.0.1"
  port: 1080

# These should be configured carefully to not get rate limited by Telegram.
# Number of messages to fetch in one batch.
# For takeout mode (use_takeout: True), this value can be greater.
fetch_batch_size: 2000

# Seconds to wait after fetching one full batch and moving on to the next one.
fetch_wait: 5

# Max number of messages to fetch across all batches before the stopping.
# This should be greater than fetch_batch_size.
# Set to 0 to never stop until all messages have been fetched.
fetch_limit: 0

publish_dir: "site"
static_dir: "static"
per_page: 500
show_day_index: True

# URL to link Telegram group names and usernames.
telegram_url: "https://t.me/{id}"

# IMPORTANT: Telegram shows the full name on your (API key holder's)
# phonebook for users who are in your phonebook.
show_sender_fullname: False

# Timezone to apply on timestamps when building the site. If no value
# is specified, all timestamps are in UTC:
# Eg: US/Eastern  Asia/Kolkata
timezone: ""

publish_rss_feed: True
rss_feed_entries: 100 # Show Latest N messages in the RSS feed.

# Root URL where the site will be hosted. No trailing slash.
site_url: "https://mysite.com"
site_name: "@{group} - Telegram group archive"
site_description: "Public archive of Telegram messages."
meta_description: "@{group} {date} - Telegram message archive."
page_title: "Page {page} - {date} @{group} Telegram message archive."
